export const GET_ZONAS = 'GET_ZONAS'
export const GET_DEPARTAMENTOS = 'GET_DEPARTAMENTOS'
export const GET_DEPARTAMENTO = 'GET_DEPARTAMENTO'
export const GET_MUNICIPIO = 'GET_MUNICIPIO'
export const GET_MUNICIPIOS = 'GET_MUNICIPIOS'
export const GET_CHARTDATA = 'GET_CHARTDATA'
export const RESET_CHARTDATA = 'RESET_CHARTDATA'
export const RESET_DEPARTAMENTOS = 'RESET_DEPARTAMENTOS'
export const RESET_DEPARTAMENTO = 'RESET_DEPARTAMENTO'
export const GET_PRECIPITACIONES = 'GET_PRECIPITACIONES'
export const GET_PRECIPITACION_DEPARTAMENTO = 'GET_PRECIPITACION_DEPARTAMENTO'
export const RESET_PRECIPITACION = 'RESET_PRECIPITACION'


