# Generated by Django 2.2.5 on 2019-09-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('extension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=200)),
                ('latitud_norte', models.CharField(max_length=6)),
                ('longitud_oeste', models.CharField(max_length=6)),
                ('msm', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('P', 'Pacifico'), ('C', 'Central'), ('R', 'Region Autonoma')], max_length=1)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('extension', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=200)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Zona')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
