# Generated by Django 2.2.5 on 2019-09-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20190926_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Departamento'),
        ),
    ]
