# Generated by Django 2.2.5 on 2019-09-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_municipio_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='cabecera',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
