# Generated by Django 2.2.5 on 2019-09-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_zona_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='extension',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zona',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='extension',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='extension',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
