# Generated by Django 2.2.5 on 2019-10-02 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20190930_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipio', to='geo.Departamento'),
        ),
    ]
